export const technicalQuestions = [
	"What are the differences between var, let, and const, and when would you use each?",
	"What are the key differences between for, while, and do...while loops? When might you choose one over the other?",
	"What is event bubbling, and how can it affect how events are handled in a nested structure?",
	"Why is event delegation useful when working with dynamic elements?",
	"What is the difference between inline event handling (onclick) and using addEventListener?",
	"What is the difference between client-side and server-side form validation, and why is it important to use both?",
	"What are the differences between querySelector, querySelectorAll, getElementById, and getElementsByClassName?",
	"Why is proper error handling essential in modern web development?",
	"How does try...catch improve error management compared to ignoring runtime errors?",
	"How does async/await simplify working with asynchronous code compared to traditional Promises?",
	"What are some common pitfalls when working with the Fetch API, and how can they be avoided?",
	"What is the difference between synchronous and asynchronous code, and why does it matter in web development?",
	"What is the difference between a callback function and a higher-order function?",
	"What is closure?",
	"What advantages does a component-based architecture provide compared to traditional HTML/CSS/JS development?",
	"How would you explain the difference between props and state to a non-technical stakeholder?",
	"When would you choose to use props over state in a component design?",
	"Reflect on one of the React applications you have built. What challenges did you face, and how did you overcome them?",
	"How do you determine whether a component should manage its own state or receive it as a prop?",
	"How does the useEffect hook help manage side effects in a React application?",
	"Can you think of a scenario where you would use useEffect without a dependency array? Why?",
	"How does the Context API differ from props drilling?",
	"What role does middleware play in an Express server?",
	"What are the key differences between NoSQL and relational databases?",
	"Why is it important to structure a database schema before performing CRUD operations?",
	"How do MongoDB's find() and findOne() methods differ?",
	"Can you describe the main difference between a .forEach loop and a .map() loop and why you would pick one versus the other?",
	"Describe the difference between a cookie, sessionStorage and localStorage.",
	"Describe the difference between <script>, <script async> and <script defer>.",
	"Why is it generally a good idea to position CSS <link>s between <head></head> and JS <script>s just before </body>? Do you know any exceptions?",
	"What are data- attributes good for?",
	"Can you explain the difference between coding a web site to be responsive versus using a mobile-first strategy?",
	"Explain hoisting.",
	"Describe event bubbling.",
	"What's the difference between an attribute and a property?",
	"Why is extending built-in JavaScript objects not a good idea?",
	"What is the difference between the document load event and the DOMContentLoaded event?",
	"What is the difference between == and ===?",
	"Make this work: duplicate([1,2,3,4,5]); // [1,2,3,4,5,1,2,3,4,5]",
	"Why is it called a Ternary expression, what does the word 'Ternary' indicate?",
	"What tools and techniques do you use debugging JavaScript code?",
	"Explain the difference between mutable and immutable objects.",
	"Explain the difference between synchronous and asynchronous functions.",
	"What is the event loop? What is the difference between the call stack and the task queue?",
	"Explain the differences in usage between function foo() {} and var foo = function() {}.",
	"Can you offer a use case for the new arrow => function syntax? How does this new syntax differ from other functions?",
	"What is different between NoSQL and SQL database? And have you face an difficulties and how did you handle it?",
	"What different between Waterfall and Agile methodology?",
	
];

export const behaviorQuestions = [
	"Give me an example of the project or initiative that you started on your own. What prompted you to get started?",
	"Tell me about a time you had to work on several projects at once. How did you handle this?",
	"Describe a situation in which you felt you had not communicated well enough. What did you do? How did you handle it?",
	"Tell me about when you had to deal with conflict within your team. How was the conflict solved? How did you handle that? How would you deal with it now?",
	"Give me an example of a time you had to take a creative and unusual approach to solve a coding problem. How did this idea come to your mind? Why do you think it was unusual?",
	"Describe a situation in which you worked diligently on a project and it did not produce the desired results. What did you learn from the experience?",
	"Give an example of an important project goal you reached and how you achieved it.",
	"Describe a situation in which you experienced difficulty in getting others to accept your ideas. What was your approach? How did this work?",
	"Tell me about a situation when you were responsible for project planning. Did everything go according to your plan? If not, why and what counteractions did you take?",
	"Tell me about a situation when you made a mistake at work. What happened and how did you deal with it?",
	"Tell me about a time when you worked with someone who was not completing their share of the work. How did you handle the situation?",
	"Describe a situation when you worked effectively under pressure. What was going on, and how did you get through it?",
	"Tell me about yourself.",
	"What do you know about our company?",
	"Why do you want to work for us?",
	"Why are you interested in this opportunity?",
	"Tell me about your dream job. What do you really want to do with your career?",
	"Tell me a time when you failed.",
	"What do you read on a regular basis?",
	"What's some critical feedback you've gotten recently?",
	"Do you have any questions?",
	"Tell me the process of developing an application from a-z",

	// TEAMWORK
	"Share an experience when you collaborated closely with someone whose personality differed significantly from yours.",
	"Discuss a situation where you encountered conflict while working in a team. How did you navigate and resolve it?",
	"Describe a time when building a relationship with a key person proved challenging. How did you eventually establish a connection?",
	"Reflect on a moment when you wished you had handled a situation differently with a colleague. What happened, and what did you learn?",
	"Talk about a time when you needed information from an unresponsive individual. How did you approach the situation?",

	// CLIENT FACING SKILLS
	"Narrate an instance when making a positive impression on a client was crucial. How did you ensure a favorable outcome?",
	"Provide an example of a situation where you did not meet a client's expectations. What actions did you take to address and rectify it?",
	"Share a story of ensuring customer satisfaction with your service.",
	"Describe an encounter with a challenging client. What was the scenario, and how did you handle it?",
	"When dealing with numerous customers, how do you prioritize and deliver excellent service to all? Define your approach to customer service.",

	// ABILITY TO ADAPT
	"Recall a high-pressure situation you faced. What challenges were present, and how did you overcome them?",
	"Discuss how your team or company underwent change and its impact on you. How did you adapt to the changes?",
	"Share your experience in your first job and the steps you took to learn the ropes.",
	"Narrate a situation where you had to think on your feet to gracefully handle a difficult or awkward situation.",
	"Reflect on a time when you faced failure. How did you manage and learn from the situation?",

	// TIME MANAGEMENT SKILLS
	"Talk about a strategic approach you took to meet all your top priorities.",
	"Describe a long-term project you managed and the strategies employed to maintain timely progress.",
	"Share an instance when your responsibilities became overwhelming. How did you handle the situation?",
	"Discuss a goal you set for yourself and the steps you took to ensure its achievement.",
	"Provide an example of managing numerous responsibilities. How did you effectively handle the workload?",

	// COMMUNICATION SKILLS
	"Narrate an occasion when you successfully persuaded someone at work to see things from your perspective.",
	"Describe a situation where you were the resident technical expert and how you ensured clear understanding for everyone.",
	"Share a time when you relied on written communication to convey complex ideas to your team.",
	"Discuss an instance where you explained something intricate to a frustrated client using effective communication.",
	"Talk about a successful presentation you gave and the factors that contributed to its success.",

	// MOTIVATION AND VALUES
	"Share your proudest professional accomplishment.",
	"Describe a time when you took initiative to correct a problem rather than waiting for someone else.",
	"Discuss an experience working under close or extremely loose supervision. How did you navigate it?",
	"Provide an example of a creative work endeavor. What was exciting or challenging about it?",
	"Reflect on a time when you were dissatisfied with your work. What improvements could have enhanced your experience?",
];
